### PR TITLE
Revert "build02: switch to btrfs"

### PR DESCRIPTION
**Pull request by zowoq**
This reverts commit 487138275cd3c02acc6847ee3c9d7cd2544400fa.

### CODE REVIEW

**Comment by Mic92** [comment]
Did btrfs cause issues?

**Comment by zowoq** [comment]
Yeah, enough that it was more hassle than what we were using originally.

**Comment by zowoq** [comment]
@Mic92 I forgot to mention that a recent change in disko seems to have broken the mdraid config that we are using here, https://github.com/nix-community/disko/commit/fe064a639319ed61cdf12b8f6eded9523abcc498 was the good commit that I ended up using for this reinstall. I didn't save the error as I assumed that I could reproduce it with the vm tests but they seem to fail with a different error than the one I saw on both good and bad commits.

**Comment by Mic92** [comment]
Is systemd in initrd enabled?

**Comment by zowoq** [comment]
No, it isn't enabled.

**Comment by Mic92** [comment]
Ok. I am not using mdraid very often, but I am also not aware of regressions at the moment.

**Pull request merged**
