### PR TITLE
Cloudflare admins

### PR DESCRIPTION
**Pull request by zimbatm**
Another part of #399

### CODE REVIEW

**Review by zowoq — APPROVED** [review]

**Comment by zowoq** [comment]
Not sure if you want to merge or close https://github.com/nix-community/infra/pull/404.

**Comment by zimbatm** [comment]
github doesn't handle PR chains very well. 404 should be merged first.

**Comment by zowoq** [comment]
Rebased due to merge conflict.

Seems this removes `account_id` from the cloudflare members?

**Comment by zimbatm** [comment]
thanks, this happens sometimes when the mapping is not done properly. the provider wants us to move to an account_id per resource anyways so I added it.

**Pull request merged**
