### PR TITLE
add kreyren

### PR DESCRIPTION
**Pull request by Kreyren**
To develop packages for various architecctures (mainly arm and riscv) and possibly co-maintain Xen

Referencing discussion in NixOS Dev: https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$ckF6NflySQx1OzXSESLoapvOxt8dqTwiOQwdfzDanKU?via=nixos.org&via=matrix.org&via=nixos.dev

### CODE REVIEW

**Comment by zowoq** [comment]
This is adding the key in the wrong place, see https://nix-community.org/community-builder .

**Comment by zowoq** [comment]
If you're looking for access to aarch64-linux that is in https://github.com/NixOS/aarch64-build-box.

**Comment by Kreyren** [comment]
> If you're looking for access to aarch64-linux that is in [NixOS/aarch64-build-box](https://github.com/NixOS/aarch64-build-box). -- @zowoq (https://github.com/nix-community/infra/pull/1396#issuecomment-2259398405)

Noted will submit it there, is this only x86?

**Comment by zowoq** [comment]
Yes.

**Comment by Kreyren** [comment]
My bad then

**Pull request closed without merging**
