### PR TITLE
nixos/community-builder: add user afh

### PR DESCRIPTION
**Pull request by afh**
The performance of the x86_64-linux builder I have access to works well enough for the majority of x86_64-linux PR work I do, yet it is impractical for longer‐running stuff like `staging` based work such as [`NixOS/nixpkgs#326249`](https://github.com/NixOS/nixpkgs/pull/326249).

Hence I kindly request access to the nixos-community builders to minimize compile times and avoid melting my laptop 😅

### CODE REVIEW

**Comment by zowoq** [comment]
Even with this machine it usually isn't feasible to build PRs targeting staging as the whole world needs to be rebuilt, for testing I'd suggest rebasing the PRs on master to save rebuilds/time.

**Comment by afh** [comment]
Thank you for merging and sharing wise words, @zowoq, much appreciated 👍 I'll think about how to reproduce the raised issue (NixOS/nixpkgs#326249) with a local set of changes based off master.

**Comment by zowoq** [comment]
@afh Please don't run nixpkgs-review directly on staging PRs, rebase the commits on master first.

**Comment by afh** [comment]
Sure thing, @zowoq, and apologies for any noise or inconvenience this may have created.

I'm looking for ways to see what packages possibly break with update of texinfo7.1.1 to 7.2 (see #368000).

For now I've cherry-picked the changes onto a separate branch based off master and build texinfo7 on the community-builder.
Can you think of procedures or ways to query for packages depending on texinfo7 that could break? Any pointers to documentation or previous PRs would be helpful and appreciated.

**Comment by zowoq** [comment]
Not really, it is in stdenv on darwin and linux so I'd expect any significant problems to surface quickly, I'd just cherry pick it to master and try building a couple of commonly used packages that depend on it explicitly.

**Pull request merged**
