### PR TITLE
marvin-mk2: update

### PR DESCRIPTION
**Pull request by timokau**
The version in #25 was mostly to get the deployment working. I think this version is ready for a test run on nixpkgs. It currently only reacts to PRs where it is summoned in the initial PR message.

- slash commands instead of @mentions
- some fixes
- training wheels removed (no toy commands anymore, does not run on issues)
- logs exceptions instead of crashing the entire server
- some fixes, improved messages

### CODE REVIEW

**Comment by timokau** [comment]
Thinking about it a bit more, its probably better to enable opt-in for pre existing PRs too before testing it on nixpkgs. Most eager testers will probably have old PRs sitting around.

**Comment by timokau** [comment]
Done.

**Comment by timokau** [comment]
Pinging @ryantm and @adisbladis since you have previously shown interest :) I'd like to get this deployed so that we can hopefully get this running on nixpkgs as a next step.

**Comment by ryantm** [comment]
@timokau I deployed it!

**Comment by timokau** [comment]
Thank you! :rocket:

**Comment by timokau** [comment]
Hm, looks like something went wrong here. No signs of life (`curl -v http://build01.nix-community.org:3001/webhook` times out). Also looks like the hydra instance has a cert issue (https://build01.nix-community.org:80/), but that's probably unrelated?

I realize that I hooked you for a quick deploy, not a big debugging session. If you do have some time for that though, it would be interesting to know if the `marvin` service is actually running and if it printed any logs to journald.

**Comment by ryantm** [comment]
```
● marvin-mk2.service - marvin-mk2 service
   Loaded: loaded (/nix/store/446nd79wijib4gl7q117057xgidk43cw-unit-marvin-mk2.service/marvin-mk2.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-06-16 17:46:09 UTC; 35min ago
 Main PID: 22142 (gmhhvbz2a3f18wl)
       IP: 0B in, 0B out
    Tasks: 2 (limit: 4915)
   Memory: 24.7M
      CPU: 273ms
   CGroup: /system.slice/marvin-mk2.service
           ├─22142 /nix/store/ffli6m23501dkiznwlkf6n4xvrj02snr-bash-4.4-p23/bin/bash -e /nix/store/gmhhvbz2a3f18wllpxa2kll78xcl2amk-unit-script-marvin-mk2-start
           └─22210 /nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/bin/python3.7 /nix/store/2jlqn4v04qnbdmd47rm8xzcbr5jg9ic8-marvin-mk2-rolling/bin/.marvin-wrapped

Jun 16 17:46:09 nix-community-build01 systemd[1]: Started marvin-mk2 service.
```

**Comment by ryantm** [comment]
There is no output in journalctl aside from it starting.

**Comment by ryantm** [comment]
I don't see anything in your configuration opening port 3001 in the firewall. It looks like it does something when I access it locally.

**Comment by timokau** [comment]
Yeah that's what I'm currently looking into. It was working before though, I wonder if @adisbladis poked a hole into the firewall before doing the last deploy?

**Comment by ryantm** [comment]
I'll do that.

**Comment by timokau** [comment]
Something like https://github.com/nix-community/infra/pull/28 should fix it

**Comment by ryantm** [comment]
Yeah, it is accessible remotely now.

**Comment by timokau** [comment]
And its [working](https://github.com/timokau/marvins-playground/pull/20#issuecomment-644941420). Thanks again!

**Pull request merged**
