### PR TITLE
flake: add nix-community/flake-compat

### PR DESCRIPTION
**Pull request by zowoq**
It's easier to be able to fall back to the old cli sometimes.

I'm fine with not adding it if anyone is 👎 .

cc @nix-community/admin

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
Don't use it but also don't object.

**Review by zimbatm — APPROVED** [review]
sure :+1:

**Comment by zowoq** [comment]
I should be able to use a couple of local workarounds instead so I don't really need this.

**Comment by zowoq** [comment]
One year later I'm still occasionally find that having flake-compat would be helpful.

@zimbatm Is https://github.com/nix-community/flake-compat still maintained or should I switch to https://github.com/edolstra/flake-compat?

**Comment by zimbatm** [comment]
Not actively maintained, but still easier to get patches merged in

**Pull request merged**
