### PR TITLE
community-builder: add btop, htop to systemPackages

### PR DESCRIPTION
**Pull request by GaetanLepage**
For easier monitoring of system resources I propose to add [btop](https://github.com/aristocratos/btop) and `htop` to the community builders packages.

### CODE REVIEW

**Comment by zowoq** [comment]
Don't need to add htop on linux, some packages are only in darwin because on linux they already included in the srvos modules we use.

Just need to add btop here:

https://github.com/nix-community/infra/blob/c7d7f1184d0c24fcd7891320843df5291f59f98c/modules/shared/community-builder.nix#L20-L30

**Comment by GaetanLepage** [comment]
> Don't need to add htop on linux, some packages are only in darwin because on linux they already included in the srvos modules we use.

Are you sure about this ?
I tried before adding it in:
```
[glepage@aarch64:~]$ htop
-bash: htop: command not found
```

**Comment by zowoq** [comment]
Wrong machine? Looks like that is https://github.com/NixOS/aarch64-build-box?

**Comment by GaetanLepage** [comment]
Oh right. I removed it.

**Pull request merged**
