### PR TITLE
build01: enable etc.overlay and userborn

### PR DESCRIPTION
**Pull request by zowoq**
@Mic92 Shall we try these for a while on one host and then maybe enable them on all the hosts?

### CODE REVIEW

**Comment by Mic92** [comment]
Two things I noticed when using it on my laptop:
It doesn't migrate old mutable state into the writable overlay (might be not an issue here).
I had some *busy mount* errors on upgrade. I think what sometimes happens that the mount point is still accessed by processes. I think some lazy unmount option is needed. This might be a problem. But I guess you could test it.

**Comment by zowoq** [comment]
> It doesn't migrate old mutable state into the writable overlay (might be not an issue here). 

Yes, shouldn't be an issue here.

> I had some _busy mount_ errors on upgrade. I think what sometimes happens that the mount point is still accessed by processes. I think some lazy unmount option is needed.

Does https://github.com/NixOS/nixpkgs/commit/7845b89e24ff9e91e6e13f66ee5a1a73958d22fb address that?

**Comment by Mic92** [comment]
> Does [NixOS/nixpkgs@7845b89](https://github.com/NixOS/nixpkgs/commit/7845b89e24ff9e91e6e13f66ee5a1a73958d22fb) address that?

Looks like this could fix the issue.

**Comment by Mic92** [comment]
I no longer have the "busy mount" issue.

**Comment by zowoq** [comment]
> > It doesn't migrate old mutable state into the writable overlay (might be not an issue here).
> 
> Yes, shouldn't be an issue here.

I forgot that we do have some mutable state that we need to handle, the ssh host key.

**Comment by Mic92** [comment]
> > > It doesn't migrate old mutable state into the writable overlay (might be not an issue here).
> > 
> > 
> > Yes, shouldn't be an issue here.
> 
> I forgot that we do have some mutable state that we need to handle, the ssh host key.

At least with sops-nix it's possible to move to age keys outside of etc and deploy ssh keys with sops. This is what I tend to do these days.

**Comment by zowoq** [comment]
Going to leave this for now.

**Pull request closed without merging**
