### PR TITLE
add treefmt-nix to repository

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by zowoq** [comment]
I've disable the treefmt check, it isn't enforceable unless we move to a PR only workflow.

TBH I think this PR have have been discussed first before it was merged.

**Comment by zimbatm** [comment]
What kind of discussion do you want to have around code formatting?

**Comment by zowoq** [comment]
- Which formatters do we want enabled.
- Should it be a CI check.
- Should it be blocking.
- Should it only check the files that changed in the commit.
- Does our workflow need to change.

**Comment by zimbatm** [comment]
I think a lot of this is based on usage. Can we not try it for a bit and see how it goes?

* Which formatters do we want enabled: one per language. Pick the most commonly used.
* Should it be a CI check: yes, it's the role of CI to test code.
* Should it be blocking: probably, but it can be annoying.
* Should it only check the files that changed in the commit: no because GitHub doesn't run CI on every commit.
* Does our workflow need to change: run `nix flake check` before pushing code?

**Comment by Mic92** [comment]
Pull requests are now mandatory for making changes to this repository.

**Comment by zowoq** [comment]
> Pull requests are now mandatory for making changes to this repository.

Does this apply to admins/owners or just to people with write permission? 

> Which formatters do we want enabled: one per language. Pick the most commonly used.

We currently have three enabled for nix. deadnix is very tedious so I want it gone: https://github.com/nix-community/infra/pull/369 

> Should it be blocking: probably, but it can be annoying.

I'd really prefer that we keep formatting and build/eval separate so we can ignore it if we want to and it doesn't break everything.

> Should it only check the files that changed in the commit: no because GitHub doesn't run CI on every commit.

I should have said PR instead of commit.

**Comment by zowoq** [comment]
> > Pull requests are now mandatory for making changes to this repository.
> 
> Does this apply to admins/owners or just to people with write permission?

Seems this just applies to write permission as I can still push to master: https://github.com/nix-community/infra/commit/d3775368953c0a8741840342cb0d3ae564b90bd8

**Comment by zowoq** [comment]
1) Check gets enabled.
2) Check gets broken on master so I disable it and say it should have been discussed first.
3) I list topics for discussion when asked.
  - (At this point I assumed we'd have a discussion and people would get a chance to approve of the changes before they happened.)
4) Check get re-enabled.
5) "Pull requests are now mandatory" workflow change.

We went from no formatting and a permissive workflow to very strict formatting and a restricted workflow. 

I think it's fair to say that these aren't insignificant changes and that they warranted discussion and consensus, that this didn't happen is bit surprising and disappointing. Frankly it makes me concerned about similar situations occurring in the future.

Also "Pull requests are now mandatory" isn't actually true so CI can still end up in a broken state.

**Comment by Mic92** [comment]
My reasoning behind adding the check was that I sometimes end up accidentally pushing to master when I actually wanted to make a PR instead (because I was on the wrong branch). I think with bors it becomes less of a burden to make all changes through a pull request. I am sorry that the rule I applied was not effective.

**Comment by zowoq** [comment]
> My reasoning behind adding the check was that I sometimes end up accidentally pushing to master when I actually wanted to make a PR instead (because I was on the wrong branch). I think with bors it becomes less of a burden to make all changes through a pull request. I am sorry that the rule I applied was not effective.

Sorry but this doesn't address my concerns.

In the interest of not wasting peoples time I'll be blunt, apologies if it comes across as rude, that isn't my intention.

- Why was this PR merged without consensus from the maintainers? I would have expected that it be left open for several days to give everyone a chance to comment.

- After I listed topics for discussion why was the check re-enabled so quickly? I would have expected a discussion and being given the chance to approve of it being re-enabled.

- Why was "pull requests are now mandatory" announced without consensus from the maintainers?

I'm not saying that any of this was done in bad faith but honestly doesn't feel like working collaboratively.

**Comment by zimbatm** [comment]
@zowoq, I think the question is what attitude we want towards the project.

In my view, the person that does the work gets precedence in the general case. That's why I was happy to see you introduce many changes to the project, and didn't require strong consensus. It's going in the right general direction and I think the work you're doing is great.

If you want you can call this change controversial and require a majority vote of the infra team, per #321. Or make a counter proposal, maybe there is a middle ground that would work for you better? Or we can try it like this for a week and see how it goes? The infra will keep changing over time so it's not like this is permanent.

**Comment by zowoq** [comment]
> I think the question is what attitude we want towards the project.

What I keep thinking is that the way all of this was done was unnecessary.

There wasn't anything gained by rushing this through.

With only a few people to consult who all seem to be responsive: why not give them a chance to do so?

> In my view, the person that does the work gets precedence in the general case.

I wouldn't consider these changes to be "general case", I think that they are very different from anything that's been merged in the last few months.

> If you want you can call this change controversial and require a majority vote of the infra team ... Or make a counter proposal, maybe there is a middle ground that would work for you better?

Should have be able to do this before it was merged and if I had said I wanted to make a counter proposal I should have been given some time to do so.

> Or we can try it like this for a week and see how it goes?

We were doing this, it broke and I disabled it.

It has been re-enabled but the underlying problem (pushing to master) hasn't been resolved.

I would have said it was still problematic and objected to it being re-enabled if I had been given a chance to do so.

I think I've found right settings to resolve it and maybe even make bors mandatory if we want (no manual merges).

It would have been much better to have discussed and been able to implement this if necessary as part of the original PR or before it was re-enabled.

Instead I've spent my time trying to figure out how to make it work even when I don't really agree with it because it seems I have no choice but to either fix it or accept that people can push unformatted changes to master and break CI.

> The infra will keep changing over time so it's not like this is permanent.

Yes, however I don't get the feeling that arguing against the something that has already been merged is likely to lead to a satisfying outcome.

I'm still concerned that we'll have similar occurrences in the future.

**Pull request merged**
