### PR TITLE
build03: update buildbot workers

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by zowoq** [comment]
@Mic92 I had bumped the number of workers to 48 but I noticed the logs were spammed with conenction failures from workers numbered >48, seems workers = threads.

**Comment by Mic92** [comment]
By default it's set to the number of cores. It can configured otherwise.

**Comment by zowoq** [comment]
I don't understand, it was configured?

**Comment by zowoq** [comment]
I understand now what you meant, needs to be set on both sides, I assumed the worker count was passed to the worker from the config on the master.

**Pull request merged**
