### PR TITLE
hydra: add Genodepkgs project

### PR DESCRIPTION
**Pull request by ehmry**
https://git.sr.ht/~ehmry/genodepkgs/tree/master/hydra.json

### CODE REVIEW

**Comment by adisbladis** [comment]
I'm a :-1: on adding repositories not living under the nix-community umbrella. I know this is already the case for the NixOS mail server but I would be reluctant to add even more.

**Comment by zimbatm** [comment]
@adisbladis is there a specific reason you had in mind?

I haven't thought this through really. It does seem to fit the mission of helping the nix ecosystem if we can help other projects.

**Comment by ehmry** [comment]
FWIW this a [NLnet funded](https://nlnet.nl/project/Genodepkgs/) project, I'd like to host it as nix-community, but microsoft code hosting is not an option.

**Comment by adisbladis** [comment]
@ehmry I've discussed it with @zimbatm and we have decided it's OK for third parties on the Hydra.

**Comment by ryantm** [comment]
@ehmry I had to [revert this](
https://github.com/nix-community/infra/commit/d8e958d7e2326bed15587cfce0f4e5bfc30f482a), because it wasn't deploying properly. The `hydra-post-init` service was exiting with a non-zero exit code with no error message right after logging that it was creating this project.

@adisbladis  were you able to deploy this earlier after merging it?

**Comment by ryantm** [comment]
Here's the log in case it helps
```
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]: Creating project:                                                             
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]: {                                                                             
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "displayname":"Genodepkgs",                                                 
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "description":"Packages for Genode",                                        
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "homepage":"https://git.sr.ht/~ehmry/genodepkgs",                           
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "enabled":"1",  
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "visible":"1",                                                             
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "declfile": "hydra.json",                
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "decltype":"git",                                       
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]:   "declvalue":"https://git.sr.ht/~ehmry/genodepkgs"                         
Dec 10 03:00:55 nix-community-build01 rkqpc6n0zzdi6ciy19mm36ik59mk82l3-unit-script-hydra-post-init-start[5832]: }                                                         
Dec 10 03:00:55 nix-community-build01 systemd[1]: hydra-post-init.service: Main process exited, code=exited, status=22/n/a                                                                  
Dec 10 03:00:55 nix-community-build01 systemd[1]: hydra-post-init.service: Failed with result 'exit-code'.                                        
Dec 10 03:00:55 nix-community-build01 systemd[1]: Failed to start hydra-post-init.service.                                                                                                    
Dec 10 03:00:55 nix-community-build01 systemd[1]: hydra-post-init.service: Consumed 550ms CPU time, received 3.4K IP traffic, sent 3.5K IP traffic.
```

**Comment by ehmry** [comment]
I think I need a newer hydra to evaluate the flake, or I need to unflake the jobset.

**Comment by zimbatm** [comment]
I think it would be enough to use nixUnstable. Any objections to https://github.com/nix-community/infra/pull/44 ?

**Comment by zimbatm** [comment]
Here is the error I found in the logs:
```
Dec 12 16:22:57 nix-community-build01 yzngdighvk1jpz035y3gljd3pv3d8wij-unit-script-postgresql-start[3991]: 2020-12-12 16:22:57.373 GMT [16509] ERROR:  new row for relation "jobsets" violates check constraint "jobsets_check"
Dec 12 16:22:57 nix-community-build01 yzngdighvk1jpz035y3gljd3pv3d8wij-unit-script-postgresql-start[3991]: 2020-12-12 16:22:57.373 GMT [16509] DETAIL:  Failing row contains (.jobsets, 71, genodepkgs, Genode Nix packages, , , 'nix flake info' returned exit code 1:
Dec 12 16:22:57 nix-community-build01 yzngdighvk1jpz035y3gljd3pv3d8wij-unit-script-postgresql-start[3991]:         warning: ignoring the use..., 1607789981, 1607789981, 1607790177, 1, 0, 1, , 3, 300, 100, null, null, null, 1, git+https://git.sr.ht/~ehmry/genodepkgs).
Dec 12 16:22:57 nix-community-build01 yzngdighvk1jpz035y3gljd3pv3d8wij-unit-script-postgresql-start[3991]: 2020-12-12 16:22:57.373 GMT [16509] STATEMENT:  UPDATE jobsets SET nixexprinput = $1, nixexprpath = $2, triggertime = $3 WHERE ( ( name = $4 AND project = $5 ) )
```

**Pull request merged**
