### PR TITLE
darwin/community-builder: add user tnias

### PR DESCRIPTION
**Pull request by tnias**
I maintain a handful of packages and would like to be able to test them a darwin environment.
Currently I have CI or someone who's package I just broke to tell me, if something darwin related broke. This is cumbersome and takes a while for each iteration.

- PRs: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Atnias
- packages: https://repology.org/projects/?maintainer=phil@grmr.de&inrepo=nix_unstable

### CODE REVIEW

**Comment by zowoq** [comment]
We don't really have specific rules for allowing access to this machine but it is basically limited to people who are well known in the nixpkgs/nixos/etc community, is there somebody who is known who can vouch for you?

**Comment by tnias** [comment]
Not sure, maybe @Mic92?

**Comment by Mic92** [comment]
@tnias Did we talk during a meetup? I am trying to remember.

**Comment by tnias** [comment]
Yes, but I am not too often in mumble/jitsi (maybe 5/year) and usually go by phil.
Not sure who, but someone suggested I should create a community builder account. Had it on my TODO list for a long time, until I had to touch something darwin related again, when I decided to at least open a PR.
If you don't feel comfortable vouching, that's fine.

**Comment by zowoq** [comment]
I rebased the PR to fix the UID number after a50a726407b5e3bbdc0ca90a60a269649917f067.

**Comment by Lassulus** [comment]
I can vouch for tnias

**Pull request merged**
