### PR TITLE
Remove marvin mk2

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by zowoq** [comment]
Might be able to drop `nixpkgs.url = "github:Mic92/nixpkgs/gidgethub";` as well, I think marvin is the only thing that needs it?

**Comment by Mic92** [comment]
good call!

**Comment by zowoq** [comment]
https://hercules-ci.com/github/nix-community/infra

Is effects broken? Looks like it is stuck waiting for `#258` to finish?

**Comment by Mic92** [comment]
I canceled it and https://hercules-ci.com/github/nix-community/infra/jobs/265 was successful.

**Pull request merged**
