### PR TITLE
darwin/community-builder: add user puckipedia

### PR DESCRIPTION
**Pull request by puckipedia**

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
I think me vouching for @puckipedia is probably unnecessary, but for protocol reasons: @puckipedia has been around in the community much more than me and has worked on a lot of projects across the Nix ecosystem. 

I personally vouch for them.

**Comment by zimbatm** [comment]
welcome puck!

**Comment by zimbatm** [comment]
deployed, let me know if ssh doesn't work

**Comment by zimbatm** [comment]
yes darwin02 is reserved for the CI builders

**Comment by zimbatm** [comment]
yeah, I think we've become a bit blind in terms of doc. Do you see where we could document things better?

**Comment by puckipedia** [comment]
The way https://nix-community.org/community-builder/ mentions the names of the machines only in context of the SSH host keys; and possibly marking usecases on https://github.com/nix-community/infra/blob/master/devdoc/hosts.md as well? but meh, it's a small issue

**Comment by zowoq** [comment]
> The way https://nix-community.org/community-builder/ mentions the names of the machines only in context of the SSH host keys

That is intentional.

> possibly marking usecases on https://github.com/nix-community/infra/blob/master/devdoc/hosts.md as well

Was removed in https://github.com/nix-community/infra/pull/738.

**Pull request merged**
