### PR TITLE
hydra: fix eval

### PR DESCRIPTION
**Pull request by zowoq**
Fixes eval failure in https://github.com/nix-community/infra/pull/263.

### CODE REVIEW

**Comment by zowoq** [comment]
@Mic92 @zimbatm 

WDTY about letting hercules build PRs from forks? Seems like it's possible with bors, might be possible with mergify as well?

**Comment by zimbatm** [comment]
We're opening ourselves to crypto attackers :)

**Comment by zowoq** [comment]
Not sure if you're just joking about attackers but with the bors GH app it looks like it requires a comment on the PR from an admin before it would be tested, the hercules org has bors enabled on a few repos and seems to work with PRs from forks.

**Comment by Mic92** [comment]
Interesting. What would need for bors?

**Comment by zowoq** [comment]
https://bors.tech/documentation/getting-started/

The docs make it look fairly simple, I'm hoping isn't more complicated than that.

**Comment by zowoq** [comment]
I've sent a request to enable bors for this repo and opened a PR with the config + trivial changes for testing. Seems the config doesn't need to be in master, just in the branch you want to build. https://github.com/nix-community/infra/pull/270

> Your CI system should build the “staging” and “trying” branches, but should not build the “staging.tmp”, “trying.tmp”, or “staging-squash-merge.tmp” branches.

Not sure how do do this or if it is even necessary with hercules?

**Pull request merged**
