### PR TITLE
darwin/community-builder: add user imincik

### PR DESCRIPTION
**Pull request by imincik**
I am nixpkgs geospatial packages maintainer and I very often struggle with fixing issues on Darwin because I don't have any access to this platform. Please grant me the access so I can better support our Darwin users.

### CODE REVIEW

**Comment by imincik** [comment]
> https://github.com/nix-community/infra/blob/7557c5dbf0ea30ad6c7a4d43fa283e4dedd96ee6/modules/darwin/community-builder/users.nix#L4
> 
> Also need to add your ssh key in `modules/darwin/community-builder/keys/imincik`.

Fixed now.
It would be really great if you can quickly create my account. I am just at ZHF meetup in Zurich and fighting with Darwin right now.

Thank you very much !

**Comment by imincik** [comment]
Great thanks.

Am I supposed to connect now ?

```
ssh imincik@darwin-build-box.nix-community.org
imincik@darwin-build-box.nix-community.org: Permission denied (publickey).
```

**Comment by zowoq** [comment]
It has been deployed, it should be working.

**Comment by imincik** [comment]
> It has been deployed, it should be working.

Great thanks. It works, I am in now.

**Pull request merged**
