### PR TITLE
nixos/community-builder: add binarycat

### PR DESCRIPTION
**Pull request by lolbinarycat**
this will be extremely helpful as currently testing anything takes forever due to a combination of old laptop and rural american internet.

### CODE REVIEW

**Comment by lolbinarycat** [comment]
@teto because you recommended i try to sign up here

**Comment by zimbatm** [comment]
Having more context would be helpful to evaluate you. Can you point us to some of the work you did?

**Comment by Mic92** [comment]
I think I would be also fine with feedback from @teto

**Comment by lolbinarycat** [comment]
@zimbatm i packaged `emacsclient-commands` and recently have been working on fixing issues with the lua ecosystem in nixpkgs, as well as trying to package several rust programs and reviewing pull requests almost every day.

all of this could be done much more efficiently if i wasn't held back by my severely underpowered laptop

**Comment by teto** [comment]
I reviewed one PR from @lolbinarycat and he reviewed one of mine, that's the amount of (sometimes rough) interaction we've had.
Could you @lolbinarycat explain what's your motivation for using/developing on nix ? How familiar with it you are ?

**Comment by lolbinarycat** [comment]
> he

i'm not a guy

> what's your motivation for using/developing on nix

i think nix is a cool project and i enjoy working on it.

i started contributing when i ran into a bug in the lua ecosystem and managed to throw together a fix for it.

i also somewhat enjoy repetative tasks such as checking PRs for simple errors.

> How familiar with it you are

i've been using nixos for a few months now, and i have a bunch of experience with lazy functional languages such as Haskell.

i've also done quite a bit of digging around in the internals of nixpkgs, so i have a good understanding of how things like envHooks work.

**Comment by lolbinarycat** [comment]
@teto is this good enough, or do i need to do something else?  to be honest there's not a ton more i can do for nixpkgs as-is other than just checking PRs for basic formatting mistakes.

**Review by zimbatm — APPROVED** [review]
ok, let's take a chance.

Usually, we only give access to well-known community members because a lot of this operates on trust.

If you could also join #nix-community:nixos.org that way we can contact you if needed.

**Comment by lolbinarycat** [comment]
i'm alr

**Comment by lolbinarycat** [comment]
i'm already in the nix matrix space (@ binarycat:snug.moe)

**Review by Mic92 — APPROVED** [review]
I also saw now enough contributions in different places.

**Pull request merged**
