### PR TITLE
Add matthiasbeyer as nix-community builder member

### PR DESCRIPTION
**Pull request by matthiasbeyer**
As suggested by @Mic92 in the nixos mumble.

I am a nixpkgs committer and am using nixos since 2014, for those of you that don't know me.

### CODE REVIEW

**Comment by zowoq** [comment]
No, hercules doesn't work for PRs from forks and I haven't got the merge queue working for forks yet either. https://github.com/nix-community/infra/issues/701

**Comment by matthiasbeyer** [comment]
Should login work now directly?

**Comment by zowoq** [comment]
Yes, it should work.

**Comment by Mic92** [comment]
```
$ cat /etc/ssh/authorized_keys.d/matthiasbeyer


ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHCUxQenEQjmGC6UckOWGXdZN7J8rVG6l5IoaJ176o+N nix community key
```

**Comment by Mic92** [comment]
your key is deployed on build01

**Comment by matthiasbeyer** [comment]
```
ssh build01.nix-community.org
Received disconnect from 94.130.143.84 port 22:2: Too many authentication failures
Disconnected from 94.130.143.84 port 22
```

With user `matthiasbeyer`.

**Comment by zowoq** [comment]
Output of `ssh -vvv build01.nix-community.org`?

**Comment by matthiasbeyer** [comment]
It tries a whole list of keys, although I set the one I added in this PR explicitly in `.ssh/config`.
But now I am getting a connection refused :shrug:

**Comment by matthiasbeyer** [comment]
Okay, issue resolved. Actually the ssh-agent did try all my other keys, although I specified the key explicitly in the config file.

`IdentityAgent none` in the `~/.ssh/config` helped me, credits to @Lassulus

**Comment by zowoq** [comment]
@matthiasbeyer Could you throttle you usage of nixpkgs-review a bit please? Using this machine to build staging PRs all the time doesn't leave much capacity for other people to use.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/252852
https://github.com/NixOS/nixpkgs/pull/252885
https://github.com/NixOS/nixpkgs/pull/252887
https://github.com/NixOS/nixpkgs/pull/252888

@matthiasbeyer I've got no idea what you doing, using this machine to post multiple nixpkgs-review run on PRs, even after they have been merged.

I've removed you access to this machine.

**Comment by matthiasbeyer** [comment]
> Could you throttle you usage of nixpkgs-review a bit please?

Yes, sure!

> even after they have been merged.

Im a posting a few in a loop (`for n in PR1 PR2 PR3 ; do nixpkgs-review...`) and if the first takes a bit longer the latter two sometimes have been merged before they even are processed.

I will use another approach.

**Comment by zowoq** [comment]
I'd very strongly suggest not using any sort of scripted approach. Also I don't think nixpkgs-review on staging PRs is a good use of resources, I'd be rather selective about testing mass rebuild/staging PRs and if you do need to test one rebase it onto master first to save some rebuilds, don't run `nixpkgs-review pr **` on it as it will build everything else on staging as well.

Re-adding you in https://github.com/nix-community/infra/pull/806.

**Comment by matthiasbeyer** [comment]
Thanks for re-adding me. I will take better care of resources, thanks for the trust!

**Pull request merged**
