### PR TITLE
sops-nix -> agenix

### PR DESCRIPTION
**Pull request by zowoq**
Any objections to moving to agenix for deployed secrets? 

We'd still be using sops for two files: `/secrets.yaml` and `/terraform/secrets.yaml`.

### CODE REVIEW

**Comment by zimbatm** [comment]
Ideally, we would use one tool everywhere. I don't care either way.

Is that your motivation to make the change?

**Comment by zowoq** [comment]
After using both for a while I just prefer it as it is simpler.

**Comment by zimbatm** [comment]
No objection. If we need KMS support down the line, we can always switch back.

**Comment by zowoq** [comment]
> After using both for a while I just prefer it as it is simpler.

Ended up that I prefer neither. I'm looking at other options but running a vault service is a bit excessive for our current needs and some of the other tools are very new so for now it is easier to go back to sops-nix.

**Pull request closed without merging**
