### PR TITLE
dev-packages: add nix-tree

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by zowoq** [comment]
bors ping

**Comment by zowoq** [comment]
bors try

**Comment by Mic92** [comment]
I added in the `Moderator` group. Is this enough?

**Comment by Mic92** [comment]
I would be interested in what bors need to function

**Comment by zowoq** [comment]
> I added in the `Moderator` group. Is this enough?

No, I think it would need to be commit access. You can delegate to a user e.g `bors delegate=zowoq`but that gives them the ability merge the PR as well.

> I would be interested in what bors need to function

If you comment `bors try` it should run and post a pass/fail comment. I'd suggest turning on required status checks  so PRs from forks will show the missing hercules jobs. 

> What do we need to put in the README or pull request for people to use this feature?

Could create a PR template with a note, something like PRs from forks don't have automatic CI, and admin needs to comment. I can send a PR for this.

**Comment by Mic92** [comment]
I added you to infra

**Comment by zowoq** [comment]
> I added you to infra

Oh, thanks. Just to be clear: I wasn't asking for access .. my intent with adding bors was to not need commit access as admins to be able to test fork PRs without needing to do it manually.

**Comment by zowoq** [comment]
bors try

**Comment by zowoq** [comment]
The required status checks won't actually go green but they avoid any confusion as just the mergify check by itself will show the PR as green. Can either merge manually with the bypass or comment for bors to merge it.

bors

**Comment by zowoq** [comment]
bors merge

**Comment by zowoq** [comment]
> Your CI system should build the “staging” and “trying” branches, but should not build the “staging.tmp”, “trying.tmp”, or “staging-squash-merge.tmp” branches.

Not sure if this is outdated docs but it didn't need any config and hercules only ran on the trying and staging branches.

**Comment by zowoq** [comment]
> 🔒 Permission denied
> 
> Existing reviewers: [click here to make zowoq a reviewer](https://app.bors.tech/repositories/48507/add-reviewer/zowoq)

Seems this link is broken, should go to https://app.bors.tech/repositories/48507/settings.

I've given myself `"member: permission to run the try and retry commands"` which is all I really need if you want to revoke my commit access.

**Comment by Mic92** [comment]
> > lock Permission denied
> > Existing reviewers: [click here to make zowoq a reviewer](https://app.bors.tech/repositories/48507/add-reviewer/zowoq)
> 
> Seems this link is broken, should go to https://app.bors.tech/repositories/48507/settings.
> 
> I've given myself `"member: permission to run the try and retry commands"` which is all I really need if you want to revoke my commit access.

Ah. This link makes more sense. I was confused.

**Pull request merged**
