### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ryantm**
This is a continuation of the work in https://github.com/nix-community/infra/commit/bb579a7db165d4205669b122303338414b22371c

### CODE REVIEW

**Comment by Mic92** [comment]
I can also recommend dependabot for updating actions: https://github.com/Mic92/nix-update/blob/master/.github/dependabot.yml

**Comment by zimbatm** [comment]
it would be good to be pure, but that will fix the immediate problem

**Comment by ryantm** [comment]
By "pure" do you mean not rely on the ever-changing nixos-unstable?

**Comment by zimbatm** [comment]
yeah, especially since we're tracking nixos-unstable, it would be good to pin it in the code

**Comment by ryantm** [comment]
I think this was the problem:

https://github.com/nix-community/infra/blob/5eee3864f3361baf3ea4a770514494b667a342c3/build01/hardware-configuration.nix#L7

**Comment by zimbatm** [comment]
indeed, always use modulesPath

**Comment by zimbatm** [comment]
https://github.com/nix-community/infra/pull/42

**Pull request merged**
