### PR TITLE
buildkite: remove

### PR DESCRIPTION
**Pull request by zowoq**
The two projects the used buildkite are inactive and their builds have been failing for a while.

### CODE REVIEW

**Comment by zimbatm** [comment]
Which projects are those? Let's archive them if they are inactive, or port them to another CI

**Comment by zowoq** [comment]
https://github.com/nix-community/nix
https://github.com/nix-community/nixpkgs-swh

https://buildkite.com/nix-community

**Comment by zimbatm** [comment]
the nix repo was my own prototype so I don't care

**Pull request merged**
