### PR TITLE
marvin: update

### PR DESCRIPTION
**Pull request by timokau**
- move usage documentation into its own document (timokau/marvin-mk2#17)
- react to commands in reviews (timokau/marvin-mk2#18)
- automatically set to `needs_work` on change requests (timokau/marvin-mk2#18)
- automatically set `needs_merge` -> `needs_review` on pushes (timokau/marvin-mk2#19)

### CODE REVIEW

**Comment by timokau** [comment]
Shouldn't be deployed yet, I forgot to check the opt-in on the automatic status transitions. Not the end of the world, but it should remain opt-in for now. I should probably double-check that before making any changes.

**Comment by timokau** [comment]
Fixed (timokau/marvin-mk2#20). Ready for deploy.

**Comment by timokau** [comment]
Now also requests reviews when the status is switched to `needs_merge` (https://github.com/timokau/marvin-mk2/pull/21).

@ryantm @adisbladis? :)

**Comment by ryantm** [comment]
@timokau I can do this now.

**Comment by ryantm** [comment]
@timokau Should be done.

**Comment by timokau** [comment]
Thanks, everything works fine: https://github.com/NixOS/nixpkgs/pull/87947#issuecomment-646872722

**Pull request merged**
