### PR TITLE
terraform: pin terraform and providers in separate flake

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by zowoq** [comment]
bors try

**Comment by zowoq** [comment]
bors try

**Comment by zowoq** [comment]
Think we might want to split the terraform shell out so we can pin it independent of the system updates.

**Comment by zowoq** [comment]
bors try

**Comment by zimbatm** [comment]
Is terraform blocking the system updates?

**Comment by zowoq** [comment]
No, this is to avoid any potential issues with the providers being constantly updated so we can use the terraform action from a known configuration.

**Comment by zowoq** [comment]
Rebased to pick up the gandi changes and dropped the commit merging shell.nix into the flake, doesn't really make a difference if it's a separate file or not.

**Comment by zowoq** [comment]
Cloudflare provider has been bumped to v4 which has breaking changes so I'll merge this in a day or two before the next flake update.

**Comment by zowoq** [comment]
bors try

**Pull request merged**
