### PR TITLE
marvin-2k: add marvin-2k.nix-community.org

### PR DESCRIPTION
**Pull request by zimbatm**
Add a layer of indirection to make the migration to build03 easier.

Please update the GitHub Webhook to point to this address first.

/cc @timokau @Mic92

part of #85

### CODE REVIEW

**Comment by zimbatm** [comment]
https://marvin-2k.nix-community.org is returning a 404 but it seems to be returning the same on port :3001

**Comment by timokau** [comment]
I have configured the bot to use the new URL for the webhook. Not that it matters, but is there a reason you picked marvin-2k instead of marvin-mk2?

It might be a good idea to transfer ownership of the GitHub app to the nix-community organization. See #85.

**Comment by Mic92** [comment]
> I have configured the bot to use the new URL for the webhook. Not that it matters, but is there a reason you picked marvin-2k instead of marvin-mk2?

false memory? we can also rename it.

**Comment by timokau** [comment]
I don't mind either way, we would just have to synchronize it.

**Pull request merged**
