### PR TITLE
build02/nixpkgs-update: enable another worker

### PR DESCRIPTION
**Pull request by zowoq**
@mic92 The oom's seem to have settled down, shall we try adding another worker?

### CODE REVIEW

**Comment by Mic92** [comment]
Maybe @ryantm is better to answer the question I don't know how much the application benefits from more workers since it will also issues build that are parallel.

**Review by ryantm — APPROVED** [review]
Sure let's try

**Comment by zowoq** [comment]
Reverted this as it was using too much memory.

**Pull request merged**
