### PR TITLE
terraform: invite admins to terraform cloud

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by zimbatm** [comment]
@nix-community/infra ^ feel free add yourself, or send a PR later if this is merged

**Comment by zowoq** [comment]
I think mine will work, if not feel free to drop it and I'll send another PR.

**Comment by zimbatm** [comment]
ok, next one of you needs to remove me. that will break the CI again. then generate a new token to put in the secrets.yaml, and then invite me again with terraform.

**Comment by zowoq** [comment]
> or do some digging to find my account ID

Looks like should be able to get this from the tf cloud api?

**Comment by zimbatm** [comment]
I managed to find and import my ID and pushed https://github.com/nix-community/infra/commit/0563ab6ba744fb0ce766109df8ff5dc2cf719574

**Pull request merged**
