### PR TITLE
modules/nixos/buildbot: switch to github app

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by Mic92** [comment]
Depends on https://github.com/Mic92/buildbot-nix/pull/156

**Comment by Mic92** [comment]
Maybe wait a couple of days with it and I have verified keys are no longer expiring.

**Comment by Mic92** [comment]
This should be the last bug fixed: https://github.com/nix-community/buildbot-nix/pull/188
It was stress tested with scripts afterwards.

**Comment by zowoq** [comment]
I'll wait a few days and then do a clean up, previous oauth app, previous buildbot user permissions, etc.

**Comment by zowoq** [comment]
I demoted the nix-community-buildbot user from owner to member after we switch to the app but now I've removed it from the org. It's token has also been revoked. The original buildbot oauth app has been deleted.

Now that buildbot.numtide and buildbot.thalheim have both switch to the github app I've removed the numtide-bot user account as a collaborator and removed the original oauth permission that was used for buildbot.thalheim.

numtide

thalheim

**Pull request merged**
