### PR TITLE
roles/watch-store: always restart

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge
Also always good to keep @domenkozar in touch about potential issues we encounter with the code.

**Comment by domenkozar** [comment]
Where there any errors you encountered?

**Comment by Mic92** [comment]
Can't tell for sure but I guess @zowoq had his reason for changing the restart type.

**Comment by domenkozar** [comment]
To achieve endless restarts, you need to disable burst limiting and increase the restart period:

```
diff --git a/nixos/modules/services/system/cachix-watch-store.nix b/nixos/modules/services/system/cachix-watch-store.nix
index ec73c0bcdcf..63713f0d3bd 100644
--- a/nixos/modules/services/system/cachix-watch-store.nix
+++ b/nixos/modules/services/system/cachix-watch-store.nix
@@ -62,7 +62,13 @@ in
       after = [ "network-online.target" ];
       path = [ config.nix.package ];
       wantedBy = [ "multi-user.target" ];
+      unitConfig = {
+        # allow to restart indefinately 
+        StartLimitIntervalSec = 0;
+      };
       serviceConfig = {
+        # don't put too much stress on the machine when restarting
+        RestartSec = 1;
         # we don't want to kill children processes as those are deployments
         KillMode = "process";
         Restart = "on-failure";
```

I'll look into the errors you're getting with watch-store on 1.4.2, thanks for letting me know!

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/226831

**Pull request merged**
